### ISSUE TITLE
Accommodate long, continuous data collections with multiple samples.

### ISSUE THREAD

**Issue by oscarbranson** [oscarbranson/latools#16]
Do people want this?

**Comment by edhathorne** [comment]
Yes please!

**Comment by oscarbranson** [comment]
Noted. This is pretty much implemented, in a pre-processing sort of way. Have a few functions to split up long files into individual samples before import. Watch this space for more info!

**Comment by oscarbranson** [comment]
Significant progress made in this direction in 0.3.9 release (addition of preprocessing.split.long_file).

Soon to be improved (0.3.10, imminent) with expansion of docs and examples.

**Comment by oscarbranson** [comment]
This has been implemented in 0.3.10, but could be made more elegant.

This will be addressed in #50.
