### ISSUE TITLE
"trace_plot()" broken (fixed)

### ISSUE THREAD

**Issue by sunwillrise** [oscarbranson/latools#34]
Hello.
In my environment, `trace_plot()` didn't plot anything on my jupyter notebook even if I put `%matplotlib inline`. 

I solved this by commenting out `plt.close(f)` in line 3365 of latools.py file.

Hope this helps.

**Comment by oscarbranson** [comment]
This is intended behaviour - trace_plots saves files, rather than displaying them all. A little cumbersome, but avoids significant performance/plotting issues when working with large datasets.

To view plots for a single, access it via the data dict, then use tplot.
